[package]
name = "bitswap"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[build-dependencies]
prost-build = "0.6"

[dependencies]
async-std = { default-features = false, version = "1.6" }
async-trait = "0.1"
cid = "0.5"
fnv = { default-features = false, version = "1.0" }
futures = { default-features = false, version = "0.3" }
libp2p-core = { default-features = false, version = "0.20" }
libp2p-swarm = "0.20"
multihash = "0.11"
prost = { default-features = false, version = "0.6" }
thiserror = "1.0"
tracing = { default-features = false, version = "0.1" }
unsigned-varint = { default-features = false, version = "0.3" }
