[package]
name = "ipfs"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
cid = { version = "*", git = "https://github.com/dvc94ch/rust-cid", branch = "implement-hash" }
env_logger = "*"
fnv = "*"
futures-preview = { version = "0.3.0-alpha.13", features = ["compat"] }
libp2p = { version = "*", git = "https://github.com/libp2p/rust-libp2p", rev = "e9535c5" }
log = "*"
multibase = "*"
multihash = "*"
parity-multiaddr = { version = "*", git = "https://github.com/libp2p/rust-libp2p", rev = "e9535c5" }
parity-multihash = { version = "*", git = "https://github.com/libp2p/rust-libp2p", rev = "e9535c5" }
protobuf = "2.0.2"
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "*"
xdg = "*"