[package]
name = "ipfs"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"

[dependencies]
cid = { version = "*", path = "../rust-cid" }
futures = "*"
libp2p = { version = "*", path = "../rust-libp2p" }
multibase = "*"
multihash = "*"
parity-multiaddr = { version = "*", path = "../rust-libp2p/misc/multiaddr" }
parity-multihash = { version = "*", path = "../rust-libp2p/misc/multihash" }
protobuf = "2.0.2"
rand = "0.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = "*"
xdg = "*"