[package]
name = "ipfs"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = []
nightly = []
all = ["rocksdb"]

[dependencies]
anyhow = { default-features = false, version = "1.0" }
async-std = { default-features = false, features = ["attributes", "std"], version = "1.6" }
async-stream = "0.2"
async-trait = "0.1"
bitswap = { path = "bitswap" }
byteorder =  { default-features = false, version = "1.3" }
cid = "0.5"
dirs = "3.0"
domain = { default-features = false, features = ["resolv"], git = "https://github.com/nlnetlabs/domain", rev="084964" }
futures = { default-features = false, features = ["compat", "io-compat"], version = "0.3.5" }
ipfs-unixfs = { path = "unixfs" }
libipld = { branch = "update_cid", default-features = false, features = ["dag-pb", "dag-json"], git = "https://github.com/ljedrz/rust-ipld" }
libp2p = "0.22"
multibase = "0.8"
multihash = "0.11"
prost = { default-features = false, version = "0.6" }
rand = { default-features = false, features = ["getrandom"], version = "0.7" }
rocksdb = { default-features = false, optional = true, version = "0.13"}
serde = { default-features = false, features = ["derive"], version = "1.0" }
serde_json = { default-features = false, version = "1.0" }
thiserror = "1.0"
tracing = { default-features = false, features = ["log"], version = "0.1" }
tracing-futures = { default-features = false, features = ["std", "futures-03"], version = "0.2" }
void = { default-features = false, version = "1.0" }

[build-dependencies]
prost-build = "0.6"

[dev-dependencies]
sha2 = "0.9"
hex-literal = "0.3"
tracing-subscriber = { version = "0.2", features = ["fmt", "tracing-log"] }

[workspace]
members = [ "bitswap", "http", "unixfs" ]

[patch.crates-io]
ctr = { git = "https://github.com/koivunej/stream-ciphers.git", branch = "ctr128-64to128" }

# at least these libp2p components need to be patched if you want to use a local version
# libp2p = { path = "../libp2p" }
# libp2p-core = { path = "../libp2p" }
# libp2p-swarm = { path = "../libp2p" }
# libp2p-floodsub = { path = "../libp2p" }
