[package]
name = "ipfs"
version = "0.1.0"
authors = ["David Craven <david@craven.ch>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[features]
default = []
nightly = []
all = ["rocksdb"]

[dependencies]
anyhow = "1.0"
async-std = { version = "1.6", features = ["attributes", "std"] }
async-trait = "0.1"
bitswap = { path = "bitswap" }
byteorder = "1.3.4"
cid = "0.5"
dirs = "3.0"
domain = { git = "https://github.com/nlnetlabs/domain", rev="084964", features = ["resolv"] }
futures = { version = "0.3.5", features = ["compat", "io-compat"] }
libipld = { git = "https://github.com/ljedrz/rust-ipld", branch = "update_cid", features = ["dag-pb", "dag-json"] }
libp2p = "0.22"
multibase = "0.8.0"
multihash = "0.11"
prost = "0.6.1"
rand = "0.7.3"
rocksdb = { version = "0.13.0", optional = true }
serde = { version = "1.0.106", features = ["derive"] }
serde_json = "1.0.51"
thiserror = "1.0.14"
tracing = { version = "0.1", features = ["log"] }
tracing-futures = { version = "0.2", default-features = false, features = ["std", "futures-03"] }
void = "1.0.2"
ipfs-unixfs = { path = "unixfs" }
async-stream = "0.2.1"

[build-dependencies]
prost-build = "0.6.1"

[dev-dependencies]
sha2 = "0.9"
hex-literal = "0.3"
tracing-subscriber = { version = "0.2", features = ["fmt", "tracing-log"] }

[workspace]
members = [ "bitswap", "http", "unixfs" ]

[patch.crates-io]
ctr = { git = "https://github.com/koivunej/stream-ciphers.git", branch = "ctr128-64to128" }

# at least these libp2p components need to be patched if you want to use a local version
# libp2p = { path = "../libp2p" }
# libp2p-core = { path = "../libp2p" }
# libp2p-swarm = { path = "../libp2p" }
# libp2p-floodsub = { path = "../libp2p" }
